title: Andy Weir - Technical Consultant
description: I Help Solve Business Problems with Software
logo: andy-weir.jpg
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme

